[package]
name = "anodos"
version = "1.0.0"
authors = ["Tom Cant"]
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
smallvec = "1.15.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
